### ISSUE TITLE
Get the status for all orders in a stock

### ISSUE THREAD

**Issue by hjr3** [rust-los-angeles/stockfighter-sdk-rs#15]
https://starfighter.readme.io/docs/status-for-all-orders-in-a-stock

**Comment by muub** [comment]
@hjr3 Can you add me as a collaborator so I can assign myself issues?

**Comment by hjr3** [comment]
@muub i missed this earlier. i sent an invite to you. accept and you should be able to collabo

**Comment by hjr3** [comment]
@muub I think this should be closed, right?

**Comment by muub** [comment]
@hjr3 Yes
